### ISSUE TITLE
Config Missing/Incorrect?

### ISSUE THREAD

**Issue by dragonshardz** [gigabit101/BaublesHud#12]
The generated config file appears to be BaublesHu**b**.cfg instead of BaublesHu**d**.cfg - maybe a typo?

**Comment by gigabit101** [comment]
yup its a typo, Not going to change it as it will break other packs, Will change it when Baubles releases for 1.15

**Comment by dragonshardz** [comment]
How will updating a mod to correctly generate its own config file "break other packs"?

**Comment by gigabit101** [comment]
It would mean that default values set by the mod pack author would not lead, I am also not updating the mod for older versions at this point.
