### ISSUE TITLE
Brakes Textures in Witchey & TCon Books

### ISSUE THREAD

**Issue by wooby6** [gigabit101/BaublesHud#2]
Tested in FTB modpack Regrowth 0.8.2
http://forum.feed-the-beast.com/threads/1-7-10-regrowth-a-wip-hqm-pack-now-listed.57184/

The books are Witchery Circle Magic & all Tcon (Tinkers Construct) books

See attached Images

Note they are only affected while Hud is displayed aka a bauble is equipped.

Tcon Broken
![tcon broken](https://cloud.githubusercontent.com/assets/12206393/10710593/7904755e-7aac-11e5-900d-e07893692c40.png)
Tcon Normal
![tcon normal](https://cloud.githubusercontent.com/assets/12206393/10710594/7906d6c8-7aac-11e5-9d6e-f3edbdb1bd15.png)
Witchery Broken
![witchery borken](https://cloud.githubusercontent.com/assets/12206393/10710595/790f1356-7aac-11e5-8003-f6da1530e878.png)
Witchery Normal
![witchery normal](https://cloud.githubusercontent.com/assets/12206393/10710596/791171b4-7aac-11e5-9453-ecb7e5472f9e.png)

**Comment by gigabit101** [comment]
simple fix will do it tomorrow
