### ISSUE TITLE
[1.10.2] Feature Request - show durability

### ISSUE THREAD

**Issue by b0bst3r** [gigabit101/BaublesHud#5]
Since BaubleStuff has gone with the idea of baublepower to give baublestuff items durability/power is there any chance you can add or config in a way to show the durability?

It's not the only mod with baubles that has a durability bar, same with most botania stuff and most likely others too.

**Comment by Fortist** [comment]
Im gonna have to agree about this now, too many mods with baubles have durability and/or power bars.
Otherwise, I dont see the point of having it on the Hud when it only tells you that you have items equipped.

**Comment by gigabit101** [comment]
fixed in new build
