### ISSUE TITLE
[1.11.2] Baubles HUD isn't working

### ISSUE THREAD

**Issue by TheSaucyWelshman** [gigabit101/BaublesHud#6]
It seems like the mod isn't loading at all. I've tested in a fresh instance with only a few mods installed and it's not working. It's not even showing up in the mod list. 

I first tried it in a pack with quite a few more mods, that's when I noticed it wasn't working. So I made a new instance in Twitch with just Baubles HUD, Baubles, JEI, and Botania and it wasn't working there either. I was about to check with Reliquary when I noticed it wasn't showing up in the mod list.

http://imgur.com/a/dSy7z

Edit: https://pastebin.com/fcenYt86

There's the log, sorry. It appears you need to make the modid all lowercase.

**Comment by gigabit101** [comment]
fixed in 4.0.1
