### ISSUE TITLE
1.11.2-4.0.2 Strange Transparency Glitch

### ISSUE THREAD

**Issue by TwitchtvCarbs** [gigabit101/BaublesHud#8]
This only happens when you don't have anything in your baubles slots.

Having a sorta annoying bug where anything that is displayed on the hud that is normally transparent has a strange gray background. The hot bar the new chat lines (when chat is closed and not focused) See gifs below.

Without any baubles equipped:
https://gyazo.com/12a82c576dfc55dd83cab83240a3a86d

With Baubles Equipped:
https://gyazo.com/84183ced515414d0bffb998599a793f8

**Comment by LukewarmYeti** [comment]
Yep having this as well, confirmed this mod, exactly how you've described it. On 1.11.2

**Comment by EPIICTHUNDERCAT** [comment]
bumping this, still an issue!
