### ISSUE TITLE
[1.12.2] HUD Box is rather... small.

### ISSUE THREAD

**Issue by SonicX8000** [gigabit101/BaublesHud#9]
Minecraft: 1.12.2
Forge: 14.23.5.2808

Mods: 4
Baubles-1.12-1.5.2
BaublesHud-1.12.2-5.0.0
Botania+r1.10-358
jei_1.12.2-4.14.4.263

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/538642660089528320/baublehudbug.PNG)

I think we gonna need a bigger box to fit those baubles. Affects both vertically & horizontally.

**Comment by gigabit101** [comment]
Yeah, I forgot about the new baubles slots.

**Comment by gigabit101** [comment]
Fixed in new build
